joint_state_publisher:
  ros__parameters:
    use_sim_time: true
    joints:
      - "crazyflie/m1_joint"
      - "crazyflie/m2_joint" 
      - "crazyflie/m3_joint"
      - "crazyflie/m4_joint"
    default_positions:
      crazyflie/m1_joint: 0.0
      crazyflie/m2_joint: 0.0
      crazyflie/m3_joint: 0.0
      crazyflie/m4_joint: 0.0
